<?xml version="1.0"?>
<robot name="roomba" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:include filename="$(find irobot_create_description)/urdf/top_plate.urdf.xacro" />

    <xacro:arg name="ns" default="target0"/>
    <xacro:arg name="color" default="white"/>
    <xacro:arg name="pole" default="1.0"/>

    <xacro:property name="M_PI" value="3.14159"/>
    <xacro:property name="wheel_radius" value="0.033" />
    <xacro:property name="wheel_length" value="0.023" />
    <xacro:property name="wheel_separation" value="0.24" />
    <xacro:property name="ns" value="$(arg ns)"/>
    <xacro:property name="obs" value="${ns.startswith('obs')}" />
    <xacro:property name="pole" value="$(arg pole)"/>

    <xacro:macro name="wheel_xmission" params="wheel_prefix">
        <transmission name="${wheel_prefix}_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="${wheel_prefix}_wheel_motor">
                <hardwareInterface>VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="${wheel_prefix}_wheel_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
        </transmission>
    </xacro:macro>

    <material name="Green">
        <color rgba="0.0 0.8 0.0 1.0"/>
    </material>

    <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin, navigation stack depends on this frame -->
    <link name="base_footprint">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="0.001" radius="0.16495"/>
            </geometry>
        </collision>
    </link>

    <!-- base link, basically the body of the Roomba -->
    <link name="base_link">
        <inertial>
            <mass value="2" />
            <origin xyz="0 0 0.0" />
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.5" />
        </inertial>

        <visual>
            <origin xyz="0 0 0.0308" rpy="0 0 1.5708" />
            <geometry>
                <mesh filename="package://irobot_create_description/meshes/$(arg color)_roomba.dae"/>
            </geometry>
        </visual>

        <collision>
            <origin xyz="0.0 0.0 0.0358" rpy="0 0 0" />
            <geometry>
                <cylinder length="0.0711632" radius="0.16495"/>
            </geometry>
        </collision>
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 0.017" rpy="0 0 0" />        
        <parent link="base_footprint"/>
        <child link="base_link" />
    </joint>

    <!-- Collision Detections -->
    <link name="front_bumper_link">
        <collision>
            <origin xyz="0.0 0.0 0.07" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://irobot_create_description/meshes/half_cylinder.stl"/>
                <!--<cylinder length="0.050" radius="0.17424"/>-->
            </geometry>
        </collision>
    </link>

    <joint name="front_bumper_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="front_bumper_link"/>
    </joint>

    <xacro:unless value="${obs}">
        <!-- random color -->
        <top_plate parent="base_link" height="0.125" red="${(pole % 0.034) >= 0.017}"/>
    </xacro:unless>


    <!-- wheels and caster wheel -->
    <link name="left_wheel_link">
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="0.01" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 1.5707 1.5707" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="DarkGray" />
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 1.5707 1.5707" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
    </link>

    <joint name="left_wheel_joint" type="continuous">
        <origin xyz="0 ${wheel_separation/2} 0.015" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="right_wheel_link">
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="0.01" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 1.5707 1.5707" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="DarkGray" />
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 1.5707 1.5707" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
    </link>

    <joint name="right_wheel_joint" type="continuous">
        <origin xyz="0 ${-wheel_separation/2} 0.015" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="caster_wheel_link">
        <inertial>
            <origin xyz="0 0 0" />
            <mass value="0.01" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
            <geometry>
                <sphere radius="0.018" />
            </geometry>
            <material name="DarkGray" />
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 1.5707 1.5707" />
            <geometry>
                <sphere radius="0.018" />
            </geometry>
        </collision>
    </link>

    <joint name="caster_wheel_joint" type="fixed">
        <origin xyz="0.12 0 0.0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="caster_wheel_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <wheel_xmission wheel_prefix="left"/>
    <wheel_xmission wheel_prefix="right"/>

    <xacro:if value="${obs}">
        <link name="pole_link">
            <inertial>
                <mass value="0.01" />
                <origin xyz="0 0 0" />
                <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.5" />
            </inertial>
            <visual>
                <origin xyz="0 0 ${pole/2.0}" rpy="0 0 0"/>
                <geometry>
                    <cylinder length="${pole}" radius="0.05"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 ${pole/2.0}" rpy="0 0 0"/>
                <geometry>
                    <cylinder length="${pole}" radius="0.05"/>
                </geometry>
            </collision>
        </link>
        <joint name="pole_joint" type="fixed">
            <origin xyz="0 0 0.0358" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="pole_link"/>
            <axis xyz="0 0 1"/>
        </joint>
    </xacro:if>

    <gazebo>
        <xacro:if value="${obs}">
            <plugin name="obstacle_roomba" filename="libobstacle_roomba.so">
                <front_bumper>base_footprint_fixed_joint_lump__front_bumper_link_collision_3</front_bumper>
                <pole_link>pole_link</pole_link>
                <!--<top_tap>base_footprint_fixed_joint_lump__top_tap_link_collision_4</top_tap>-->
                <wheel_separation>${wheel_separation}</wheel_separation>
                <wheel_radius>${wheel_radius}</wheel_radius>
                <left_joint>left_wheel_joint</left_joint>
                <right_joint>right_wheel_joint</right_joint>
                <lin_vel>0.33</lin_vel>
                <ang_vel>0.066</ang_vel>
                <bound>10.0</bound>
            </plugin>
        </xacro:if>

        <xacro:unless value="${obs}">
            <plugin name="target_roomba" filename="libtarget_roomba.so">
                <front_bumper>front_bumper_link</front_bumper>
                <top_tap>top_plate_link</top_tap>
                <wheel_separation>${wheel_separation}</wheel_separation>
                <wheel_radius>${wheel_radius}</wheel_radius>
                <left_joint>left_wheel_joint</left_joint>
                <right_joint>right_wheel_joint</right_joint>
                <lin_vel>0.33</lin_vel>
                <ang_vel>1.375</ang_vel>
                <bound>10.0</bound>
            </plugin>
        </xacro:unless>
    </gazebo>

    <gazebo reference="front_bumper_link">
        <sensor name="front_bumper" type="contact">
            <always_on>true</always_on>
            <update_rate>50</update_rate>
            <contact>
                <!-- unfortunately, gazebo lumps fixed joints into ridiculous names -->
                <collision>base_footprint_fixed_joint_lump__front_bumper_link_collision_3</collision>
            </contact>
            <plugin name="front_bumper" filename="libgazebo_ros_bumper.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>50</updateRate>
                <bumperTopicName>${ns}/front_bumper</bumperTopicName>
                <frameName>${ns}</frameName>
            </plugin>
        </sensor>
    </gazebo>

    <xacro:unless value="${obs}">
        <gazebo reference="top_plate_link">
            <sensor name="top_tap" type="contact">
                <always_on>true</always_on>
                <update_rate>50</update_rate>
                <contact>
                    <!-- unfortunately, gazebo lumps fixed joints into ridiculous names -->
                    <collision>base_footprint_fixed_joint_lump__top_plate_link_collision_4</collision>
                </contact>
                <plugin name="top_tap" filename="libgazebo_ros_bumper.so">
                    <alwaysOn>true</alwaysOn>
                    <updateRate>50</updateRate>
                    <bumperTopicName>${ns}/top_tap</bumperTopicName>
                    <frameName>${ns}</frameName>
                </plugin>
            </sensor>
        </gazebo>
    </xacro:unless>

</robot>
