odom_frame: odom
base_link_frame: base_link
world_frame: map

print_diagnostics: true
publish_tf: true
two_d_mode: false

# odom from vel+optflow, etc.
# trust everything
odom0: /noisy_odom #(odom->base_link
odom0_config: [false,false,false, #lpos
               false,false,false, #apos
               true,true,true, #lvel
               true,true,true, #avel
               false,false,false] #lacc
odom0_differential: true
odom0_queue_size: 10

# gridfinder, position only
odom1: /grid_odom
odom1_config: [true,true,false,
               false,false,false,
               false,false,false,
               false,false,false,
               false,false,false]
odom1_differential: false
odom1_queue_size: 10

# ++ imu data
